version: '3'
services:

    server:
        build:
            dockerfile: Dockerfile
            context: .
    tomcat:
        restart: always
        image: tomcat
        ports:
          - '7879:7879'
